### ISSUE TITLE
handle() method in CommandHandler

### ISSUE THREAD

**Issue by ceesvanegmond** [SimpleBus/CommandBus#3]
The ```handle()``` method in ```SimpleBus\Command\Handler\CommandHandler``` expects an implementation of the ```SimpleBus\Command\Command``` interface as ```Command $command````.

When having this command and handler

```php
<?php

use SimpleBus\Command\Command;

class RegisterUserCommand implements Command
{
    const NAME = 'register_user';

    public $email;

    public function name()
    {
        return self::NAME;
    }
}
```

```php
<?php

use SimpleBus\Command\Command;
use SimpleBus\Command\Handler\CommandHandler;

class RegisterUserCommandHandler implements CommandHandler
{
    public function handle(Command $command)
    {
        // do anything to handle the command
    }
}
```

Wouldn't it be better in the ```RegisterUserCommandHandler``` to expect an implementation of ```SimpleBus\Command\Command\RegisterUserCommand``` instead of the interface ```SimpleBus\Command\Command```? Like so:

```php
<?php

use SimpleBus\Command\Command;
use Acme\Demo\RegisterUserCommand;

class RegisterUserCommandHandler implements CommandHandler
{
    public function handle(RegisterUserCommand $command)
    {
        // do anything to handle the command
    }
}
```

In the last case the ```RegisterUserCommandHandler``` ```handle()``` must be an implementation of ```RegisterUserCommand```. When doing this you know for sure that the ```$command``` has the right implementation. 

In the current usecase, I can have another command using the ```RegisterUserCommandHandler```, because it als implements the ```Command``` interface.

I'm wondering why the choice is made to use ```Command``` implementation instead of the concrete class.

**Comment by ceesvanegmond** [comment]
Ah, I just noticed https://github.com/SimpleBus/CommandBus/pull/2. Thanks for the explanation anyway!

**Comment by matthiasnoback** [comment]
Thanks for reporting it anyway, and for taking the time to write it up.

**Comment by matthiasnoback** [comment]
And for using SimpleBus of course!
